name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode 16.2
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    
    - name: Build documentation
      run: |
        # Build only our target's documentation, excluding dependencies
        swift package --allow-writing-to-directory docs \
          generate-documentation \
          --target HDXLXCTestRetrofit \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path hdxl-xctest-retrofit \
          --output-path docs \
          --fallback-display-name "HDXLXCTestRetrofit" \
          --fallback-bundle-identifier "com.hdxl.xctest-retrofit" \
          --fallback-bundle-version "1.0.0"
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4